import turtle
s=100
def rectangle():
  turtle.color("Blue")
  turtle.forward(s) 
  turtle.left(90) 
  turtle.forward(s) 
  turtle.left(90) 
  turtle.forward(s) 
  turtle.left(90) 
  turtle.forward(s)
  turtle.right(180)
  turtle.forward(100)
  turtle.right(90)
  turtle.forward(50)
def hanger():
  turtle.left(90)
  turtle.forward(200)
  turtle.right(90)
  turtle.forward(100)
  turtle.right(90)
  turtle.forward(40)
  turtle.left(90)
def circle():
  turtle.circle(-20)
  turtle.circle(-20,180)
def neck():
  turtle.right(180)
  turtle.right(90)
  turtle.forward(100)
def rhand():
  turtle.backward(70)
  turtle.left(45)
  turtle.forward(50)
def lhand():
  turtle.backward(50)
  turtle.right(90)
  turtle.forward(50)
def rleg():
  turtle.backward(50)
  turtle.left(45)
  turtle.forward(70)
  turtle.left(45)
  turtle.forward(50)
def lleg():
  turtle.backward(50)
  turtle.right(90)
  turtle.forward(50)
# rectangle()
# hanger()
# circle()
# neck()
# rhand()
# lhand()
# rleg()
# lleg()
